{
 "title": "Orange Prepaid Poland",
 "tags": [
  "4g",
  "lte",
  "orange.pl",
  "mobile data",
  "5g",
  "prepaid"
 ],
 "time": { "from": "now-2d", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "billing_account_code",
    "label": "Phone Number",
    "query": {
     "query": "label_values(orangepl_billing_accounts_info,billing_account_code)"
    }
   },
   { "name": "interval", "label": "Interval", "query": "1h,6h,12h,1d,7d,14d,30d" }
  ]
 },
 "panels": [
  {
   "title": "Main Account Balance",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyPLN" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by(billing_account_code) (orangepl_prepaid_cash_pln{billing_account_code=~\"$billing_account_code\", cash_type=\"gc\"})",
     "legendFormat": "{{billing_account_code}}"
    }
   ]
  },
  {
   "title": "Promotional Account Balance",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyPLN" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by(billing_account_code) (orangepl_prepaid_cash_pln{billing_account_code=~\"$billing_account_code\", cash_type=\"pc\"})",
     "legendFormat": "{{billing_account_code}}"
    }
   ]
  },
  {
   "title": "Prepaid Non-Roaming Data Allowance",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by(billing_account_code) (orangepl_prepaid_allowance_data_bytes{data_type=\"DATA\", billing_account_code=~\"$billing_account_code\"})",
     "legendFormat": "{{billing_account_code}}"
    }
   ]
  },
  {
   "title": "Prepaid Roaming Data Allowance",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by(billing_account_code) (orangepl_prepaid_allowance_data_bytes{data_type=\"DATA_R\", billing_account_code=~\"$billing_account_code\"})",
     "legendFormat": "{{billing_account_code}}"
    }
   ]
  },
  {
   "title": "Allowance Expiration Dates",
   "type": "stat",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(billing_account_code, description) (orangepl_prepaid_allowance_data_item_expiry_date{data_type=\"DATA\", billing_account_code=~\"$billing_account_code\"} * 1000)",
     "legendFormat": "{{billing_account_code}} ({{description}})"
    }
   ]
  },
  {
   "title": "Prepaid Non-Roaming Data Allowance Remaining",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max by(billing_account_code) (orangepl_prepaid_allowance_data_bytes{data_type=\"DATA\", billing_account_code=~\"$billing_account_code\"})",
     "legendFormat": "{{billing_account_code}}"
    }
   ]
  },
  {
   "title": "Prepaid Roaming Data Allowance Remaining",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max by(billing_account_code) (orangepl_prepaid_allowance_data_bytes{data_type=\"DATA_R\", billing_account_code=~\"$billing_account_code\"})",
     "legendFormat": "{{billing_account_code}}"
    }
   ]
  },
  {
   "title": "Prepaid Non-Roaming Data Allowance Changes",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max by(billing_account_code) (delta(orangepl_prepaid_allowance_data_bytes{data_type=\"DATA\", billing_account_code=~\"$billing_account_code\"}[$__interval]))",
     "legendFormat": "{{billing_account_code}}"
    }
   ]
  },
  {
   "title": "Prepaid Non-Roaming Data Allowance Consumption",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "(max by(billing_account_code) (delta(orangepl_prepaid_allowance_data_bytes{data_type=\"DATA\", billing_account_code=~\"$billing_account_code\"}[$__interval])) < 0) * -1",
     "legendFormat": "{{billing_account_code}}"
    }
   ]
  },
  {
   "title": "Allowance Expiration Date Timeline",
   "type": "state-timeline",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsLocal" } },
   "targets": [
    {
     "expr": "sum by(billing_account_code, description) (orangepl_prepaid_allowance_data_item_expiry_date{data_type=\"DATA\", billing_account_code=~\"$billing_account_code\"}) * 1000",
     "legendFormat": "{{billing_account_code}} ({{description}})"
    }
   ]
  }
 ]
}